# .github/workflows/firebase-preview.yml
name: Preview Deploy to Firebase Hosting on PR

on: pull_request

permissions:
  contents: read
  pull-requests: write

jobs:
  build_and_preview:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Build Flutter Web
        run: flutter build web

      - name: Deploy to Firebase Preview Channel
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          npm install -g firebase-tools
          firebase hosting:channel:deploy pr-${{ github.event.pull_request.number }} --project ajportfolio-e9a77
